package model;
// Generated 16/05/2016 03:40:10 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Imagen generated by hbm2java
 */
@Entity
@Table(name = "imagen", schema = "documentos")
public class Imagen implements java.io.Serializable {

    private int id;
    private MimeType mimeType;
    private String nombre;
    private byte[] contenido;
    private String ruta;

    public Imagen() {
    }

    public Imagen(int id, MimeType mimeType, String nombre, byte[] contenido, String ruta) {
        this.id = id;
        this.mimeType = mimeType;
        this.nombre = nombre;
        this.contenido = contenido;
        this.ruta = ruta;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "mime_type_id", nullable = false)
    public MimeType getMimeType() {
        return this.mimeType;
    }

    public void setMimeType(MimeType mimeType) {
        this.mimeType = mimeType;
    }

    @Column(name = "nombre", nullable = false)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "contenido", nullable = false)
    public byte[] getContenido() {
        return this.contenido;
    }

    public void setContenido(byte[] contenido) {
        this.contenido = contenido;
    }

    @Column(name = "ruta", nullable = false)
    public String getRuta() {
        return this.ruta;
    }

    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

}
