package model;
// Generated 16/05/2016 03:40:10 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MimeType generated by hbm2java
 */
@Entity
@Table(name = "mime_type",
       schema = "documentos",
       uniqueConstraints = @UniqueConstraint(columnNames = "nombre"))
public class MimeType implements java.io.Serializable {

    private int id;
    private String nombre;
    private String extension;

    public MimeType() {
    }

    public MimeType(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    public MimeType(int id, String nombre, String extension) {
        this.id = id;
        this.nombre = nombre;
        this.extension = extension;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "nombre", unique = true, nullable = false)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "extension")
    public String getExtension() {
        return this.extension;
    }

    public void setExtension(String extension) {
        this.extension = extension;
    }

}
